### ISSUE TITLE
Fixed in 11.1 EN

### ISSUE THREAD

**Issue by Desperationis** [jamestiotio/CITM#7]
As far as I can tell, this type of attack is most likely fixed in 11.1.0; Nonce values are now used to make it near impossible to replay packets. Such a shame.

**Comment by jamestiotio** [comment]
Hi @Desperationis, thank you for informing me about this. I noticed that this method didn't work in the latest version of Battle Cats as well, and thus I would assume that it's patched. I have updated the main README file accordingly.

**Comment by Desperationis** [comment]
No problem. As for the specific version, I believe it was 11.1; It worked just fine in 11.0 right before 11.1 came out

**Comment by jamestiotio** [comment]
Ah okay, thank you for informing me about the specific version.

Cheers!
